### ISSUE TITLE
buyPrice and sellPrice

### ISSUE THREAD

**Issue by dineshgola025** [CraigGrantNow/cgnow#1]
On buy and sell tab it only shows buyPrice and sellPrice upto 4 decimal places plz fix it to 8 decimal

**Comment by CraigGrantNow** [comment]
Hello @dineshgola025 ,

I will take a look into this. :- )

Thank you,
BCP

**Comment by CraigGrantNow** [comment]
@dineshgola025 This will be fixed on the upcoming "BeNow" smart contract exchange.
